### ISSUE TITLE
make rpms failed

### ISSUE THREAD

**Issue by KnightKu** [cea-hpc/lcap#1]
`make[3]: Entering directory `/tmp/lcap/rpms/BUILD/lcap-0.1/src/common'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../src/include     -g -O2 -MT lcap_log.lo -MD -MP -MF .deps/lcap_log.Tpo -c -o lcap_log.lo lcap_log.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src/include -g -O2 -MT lcap_log.lo -MD -MP -MF .deps/lcap_log.Tpo -c lcap_log.c  -fPIC -DPIC -o .libs/lcap_log.o
lcap_log.c:35:22: error: lcap_log.h: No such file or directory
lcap_log.c:40: error: expected specifier-qualifier-list before 'lcap_loglevel_t'
lcap_log.c:62: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'CurrentLogLevel'
lcap_log.c: In function 'stderr_log':
lcap_log.c:82: error: 'const struct lcap_log_rec' has no member named 'clr_pid'
lcap_log.c:83: error: 'const struct lcap_log_rec' has no member named 'clr_tid'
lcap_log.c:84: error: 'const struct lcap_log_rec' has no member named 'clr_level'
lcap_log.c:85: error: 'const struct lcap_log_rec' has no member named 'clr_func'
lcap_log.c:85: error: 'const struct lcap_log_rec' has no member named 'clr_msg'
lcap_log.c: At top level:
lcap_log.c:109: error: expected ')' before 'level'
lcap_log.c: In function 'syslog_log':
lcap_log.c:138: error: 'const struct lcap_log_rec' has no member named 'clr_level'
lcap_log.c:140: error: 'const struct lcap_log_rec' has no member named 'clr_pid'
lcap_log.c:141: error: 'const struct lcap_log_rec' has no member named 'clr_tid'
lcap_log.c:142: error: 'const struct lcap_log_rec' has no member named 'clr_level'
lcap_log.c:143: error: 'const struct lcap_log_rec' has no member named 'clr_func'
lcap_log.c:143: error: 'const struct lcap_log_rec' has no member named 'clr_msg'
lcap_log.c: At top level:
lcap_log.c:187: error: expected ')' before 'loglevel'
lcap_log.c: In function 'lcap_set_loglevel':
lcap_log.c:224: error: 'CurrentLogLevel' undeclared (first use in this function)
lcap_log.c:224: error: (Each undeclared identifier is reported only once
lcap_log.c:224: error: for each function it appears in.)
lcap_log.c:224: error: 'LCAPLOG_ERR' undeclared (first use in this function)
lcap_log.c:228: error: 'LCAPLOG_NFO' undeclared (first use in this function)
lcap_log.c:232: error: 'LCAPLOG_VRB' undeclared (first use in this function)
lcap_log.c:236: error: 'LCAPLOG_DBG' undeclared (first use in this function)
lcap_log.c: In function 'lcap_get_loglevel':
lcap_log.c:243: error: 'CurrentLogLevel' undeclared (first use in this function)
make[3]: *** [lcap_log.lo] Error 1
make[3]: Leaving directory `/tmp/lcap/rpms/BUILD/lcap-0.1/src/common'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/lcap/rpms/BUILD/lcap-0.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/lcap/rpms/BUILD/lcap-0.1'
error: Bad exit status from /var/tmp/rpm-tmp.GOPXCU (%build)

RPM build errors:
    Macro %purpose has empty body
    Macro %purpose has empty body
    Bad exit status from /var/tmp/rpm-tmp.GOPXCU (%build)
make: *** [rpms] Error 1
`

**Comment by hdoreau** [comment]
Thanks for reporting this. As you can see I had to pause the project for a while. If you can submit a patch fixing this error I'd be very happy to accept it. Otherwise I'll work on it when time permits but cannot give you any ETA... Please also note that beyond package generation, you may encounter various limitations/issues with this version.

**Comment by KnightKu** [comment]
Thanks for this commit, the problem is gone.
Will do further testing, and will report if there are other problems then.
